version: "3.9"
services:
  db:
    image: "mariadb:10.11"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    env_file:
      - ".env"
    volumes:
      - "db-store:/var/lib/mysql"
    ports:
      - "23306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      start_period: "10s"
      interval: "10s"
      retries: 30

  migrate:
    image: ghcr.io/canpok1/my-home-dashboard/migrate:latest
    env_file:
      - ".env"
    command: ["migrate-up"]

  dashboard:
    image: ghcr.io/canpok1/my-home-dashboard/dashboard:latest
    ports:
      - "13000:3000"
    env_file:
      - ".env"

volumes:
  db-store:
