version: "3.9"
services:
  dashboard:
    image: ghcr.io/canpok1/my-home-dashboard/dashboard:latest
    env_file:
      - ".env"
    restart: always

  admin:
    image: ghcr.io/canpok1/my-home-dashboard/admin:latest
    env_file:
      - ".env"
    restart: always

networks:
  default:
    external:
      name: common-database-network
