version: "3.9"
services:
  dev:
    build:
      context: ./dev
      dockerfile: Dockerfile
    environment:
      DB_URL_FOR_PRISMA: "mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST_ON_DOCKER_NETWORK}:${DB_PORT_ON_DOCKER_NETWORK}/${DB_NAME}"
  db:
    image: "mariadb:10.11"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "db-store:/var/lib/mysql"
    ports:
      - "${DB_PORT_ON_LOCAL}:${DB_PORT_ON_DOCKER_NETWORK}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      start_period: "10s"
      interval: "10s"
      retries: 30
  migrate:
    build:
      context: ./migrate
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./migrate/ddl"
        target: "${DDL_DIR_ON_CONTAINER}"
  tbls:
    image: ghcr.io/k1low/tbls:latest
    working_dir: "/work"
    volumes:
      - type: bind
        source: "."
        target: "/work"
volumes:
  db-store:
