version: "3.9"
services:
  dev:
    build:
      context: ./dev
      dockerfile: Dockerfile
  db:
    image: "mariadb:10.11"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "db-store:/var/lib/mysql"
    ports:
      - "${DB_PORT_ON_LOCAL}:${DB_PORT_ON_DOCKER_NETWORK}"
  migration:
    build:
      context: ./migration
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./migration/ddl"
        target: "${DDL_DIR_ON_CONTAINER}"
volumes:
  db-store:
