version: "3.9"
services:
  db:
    image: "mariadb:10.11"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    env_file:
      - ".env"
    volumes:
      - "db-store:/var/lib/mysql"
    ports:
      - "53306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      start_period: "10s"
      interval: "10s"
      retries: 30
  dashboard:
    image: ghcr.io/canpok1/my-home-dashboard/dashboard:latest
    ports:
      - "80:80"
    env_file:
      - ".env"
  electricity-fetcher:
    image: ghcr.io/canpok1/my-home-dashboard/electricity-fetcher:latest
    # ローカルでビルドしたイメージの動作確認用
    # build:
    #   context: "../"
    #   dockerfile: "electricity-fetcher/Dockerfile"
    env_file:
      - ".env"

volumes:
  db-store:
