apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-home-dashboard-bot-event
spec:
  timeZone: "Asia/Tokyo"
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-home-dashboard-bot
              image: ghcr.io/canpok1/my-home-dashboard/bot:latest
              env:
                - name: APP_NAME
                  value: "bot_mini_pc"
                - name: LOG_LEVEL
                  value: "info"
                - name: SLACK_LOG_LEVEL
                  value: "error"
                - name: SLACK_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: my-home-dashboard-slack
                      key: webhook-url
                - name: ENCRYPTION_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: my-home-dashboard-common
                      key: encryption-password
                - name: DB_URL_FOR_PRISMA
                  valueFrom:
                    secretKeyRef:
                      name: my-home-dashboard-db
                      key: prisma-url
          restartPolicy: OnFailure
