CREATE TABLE electricity_monthly_usages (
  usage_year INT UNSIGNED NOT NULL COMMENT '年',
  usage_month INT UNSIGNED NOT NULL COMMENT '月',
  usage_day_count INT UNSIGNED NOT NULL COMMENT '使用日数',
  usage_kwh INT UNSIGNED NOT NULL COMMENT '使用量(kWh)',
  usage_yen INT UNSIGNED NOT NULL COMMENT '料金(円)',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',

  PRIMARY KEY (usage_year, usage_month)
);
