CREATE TABLE cost_types (
  id SERIAL NOT NULL COMMENT '費用種別ID',
  type_name VARCHAR(255) NOT NULL COMMENT '費用種別名',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時(UTC)',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時(UTC)',

  PRIMARY KEY (id),
  CONSTRAINT uk_cost_types_type_name UNIQUE (type_name)
)
COMMENT '費用種別'
;
