CREATE TABLE line_channels (
  id VARCHAR(256) NOT NULL COMMENT 'LINEチャンネルID',
  memo TEXT COMMENT 'メモ',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',

  PRIMARY KEY (id)
)
COMMENT 'LINEチャンネル'
;
