version: "3.9"
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      DB_URL_FOR_PRISMA: "mysql://service:password@db:3306/my-home"

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: "mariadb:10.11"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "my-home"
      MYSQL_USER: "service"
      MYSQL_PASSWORD: "password"
    volumes:
      - "db-store:/var/lib/mysql"
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      start_period: "10s"
      interval: "10s"
      retries: 30
volumes:
  db-store:
