name: code-build-deployment

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MYSQL_DATABASE: my-home
      MYSQL_USER: service
      MYSQL_PASSWORD: password
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MIGRATE_VERSION: 4.18.1
      TBLS_VERSION: 1.79.0
    services:
      db-test:
        image: mariadb:10.11
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MYSQL_DATABASE: my-home
          MYSQL_USER: service
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v5

      - name: install migrate command
        run: |
          curl -o migrate.deb -L https://github.com/golang-migrate/migrate/releases/download/v${MIGRATE_VERSION}/migrate.linux-amd64.deb
          sudo apt install ./migrate.deb
          rm migrate.deb

      - name: install tbls command
        run: |
          curl -o tbls.deb -L https://github.com/k1LoW/tbls/releases/download/v${TBLS_VERSION}/tbls_${TBLS_VERSION}-1_amd64.deb
          sudo apt install ./tbls.deb
          rm tbls.deb

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run db:test:migrate:up-all

      - run: npm run db:test:lint

      - run: npm run db:test:doc

      - run: npm run db:test:seed

      - run: npm run -w lib build

      - run: npm run test:coverage

      - run: npm run typecheck

      - run: npm run lint

      - run: npm run db:test:migrate:down-all

      - name: archive db docs
        uses: actions/upload-artifact@v4
        with:
          name: db-docs
          path: public/database

      - name: archive coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: public/coverage

      - uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            **/node_modules
          key: ${{ steps.cache.outputs.cache-primary-key }}

  build:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        app: [admin, bot, dashboard, fetcher, notifier]
    steps:
      - uses: actions/checkout@v5
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/${{ matrix.app }}/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.app }}:latest

  migrate_db:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    environment: production-web
    env:
      MYSQL_DATABASE: my-home
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MIGRATE_VERSION: 4.18.1
    steps:
      - uses: actions/checkout@v5

      - name: install migrate command
        run: |
          curl -o migrate.deb -L https://github.com/golang-migrate/migrate/releases/download/v${MIGRATE_VERSION}/migrate.linux-amd64.deb
          sudo apt install ./migrate.deb
          rm migrate.deb

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run db:update

  deploy_web:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    environment: production-web
    steps:
      - name: Deploy to web server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ vars.DEPLOY_DIR }}
            git pull origin main
            cd production/web
            docker-compose pull
            docker-compose up -d
            docker system prune -f

  deploy_public:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v5

      - name: Download coverage reports
        uses: actions/download-artifact@v5
        with:
          name: coverage-reports
          path: public/coverage

      - name: Download db docs
        uses: actions/download-artifact@v5
        with:
          name: db-docs
          path: public/database

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true
