name: CI for development

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: |
            node_modules
            dashboard/node_modules
            electricity-fetcher/node_modules
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run -w lib build

      - run: npm run typecheck

      - run: npm run lint

      - uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            node_modules
            dashboard/node_modules
          key: ${{ steps.cache.outputs.cache-primary-key }}

  db_test:
    runs-on: ubuntu-latest
    env:
      MYSQL_DATABASE: my-home
      MYSQL_USER: service
      MYSQL_PASSWORD: password
      MYSQL_HOST_ON_DOCKER_NETWORK: localhost
      MYSQL_PORT_ON_DOCKER_NETWORK: 3306
    services:
      db:
        image: mariadb:10.11
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MYSQL_DATABASE: my-home
          MYSQL_USER: service
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true

      - name: Get Go Version
        id: get-go-version
        run: echo "version=$(go env GOVERSION)" >> $GITHUB_OUTPUT

      - name: Get Go Path
        id: get-go-path
        run: echo "path=$(go env GOPATH)" >> $GITHUB_OUTPUT

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: |
            ${{ steps.get-go-path.outputs.path }}/bin/migrate
            ${{ steps.get-go-path.outputs.path }}/bin/tbls
          key: ${{ steps.get-go-version.outputs.version }}-migrate-tbls

      - name: install migrate command
        id: install-migrate
        run: |
          if ! which migrate; then
            go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
          fi
          echo "path=$(which migrate)" >> $GITHUB_OUTPUT

      - name: install tbls command
        id: install-tbls
        run: |
          if ! which tbls; then
            go install github.com/k1LoW/tbls@latest
          fi
          echo "path=$(which tbls)" >> $GITHUB_OUTPUT

      - name: test migrate up
        working-directory: ./db
        run: make migrate-up

      - name: lint for database
        working-directory: ./db
        run: make lint

      - name: check diff between db and document
        working-directory: ./db
        run: make diff

      - name: test migrate down all
        working-directory: ./db
        run: make migrate options="down -all"

      - uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            ${{ steps.install-migrate.outputs.path }}
            ${{ steps.install-tbls.outputs.path }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

  build_and_push_to_ghcr:
    runs-on: ubuntu-latest
    needs: [code_test, db_test]
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        app: [dashboard, electricity-fetcher]
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.app }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.app }}:latest
